--여기는 관리자화면입니다

CREATE TABLESPACE myIOTs
DATAFILE 'D:/bizwork/Ordata/myIOTs.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 1M;

CREATE USER myIoUser IDENTIFIED BY 1234
DEFAULT TABLESPACE myIOTs;

GRANT DBA TO myIoUser;

